### ISSUE TITLE
Request: would you be willing to support common directories

### ISSUE THREAD

**Issue by quadroli** [likle/cwalk#55]
Hello, I came across cwalk whilst I was searching for a C equivalent of [dirs-rs](https://github.com/dirs-dev/dirs-rs) which provides a cross platform way to access common folders such as .config (or their equivalent) on Mac, Linux and Windows.

Would it be possible to enhance cwalk to support this as well ?
I have searched extensively and I'm yet to come across such a C library, thank you.

**Comment by likle** [comment]
Hey @quadroli ! I have no issue with the functionality itself, however, I believe dirs-rs uses [SHGetKnownFolderPath](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath) to achieve this functionality. cwalk currently does not have any dependencies on the Windows API and I am quite hesitant to add that - not solely due to the reason that all functionality can be used from one platform for another platform so far.

If you just want the config folder, I would suggest to write a simple function for yourself. I _think_ the paths should be like this:

Linux: `$XDG_CONFIG_HOME` or fallback to `$HOME/.config` if not set.

macOS: (According to [The Mac Application Environment](https://developer.apple.com/library/archive/documentation/General/Conceptual/MOSXAppProgrammingGuide/AppRuntime/AppRuntime.html) it is `$HOME/Library/Application Support`, maybe there are more native ways to get that folder path - see [this](https://stackoverflow.com/questions/5123361/finding-library-application-support-from-c). I read that it is not as consistent on macOS as one wish it to be, some applications using `$HOME/.config` as well. I personally would probably use the same code as in Linux, but a macOS user can probably give you better advice here.


Windows: `SHGetKnownFolderPath(FOLDERID_RoamingAppData, 0, NULL, &path);`

I guess you can use `getenv` for the env vars. Given that, it should not be too complicated to get it to work. I hope this helps you at least somewhat.

**Comment by quadroli** [comment]
Yapp, Thank you for the research!
I suppose getting the path to .config is trivial. However in the pursuit for dirs-rs for C, one may be tempted to whip up a lib for it.
Thank you for the speedy response though. I appreciate 👏🏼

**Comment by quadroli** [comment]
In a stroke of good fortune, I finally happened to come across such a lib: [cfgpath](https://github.com/Malvineous/cfgpath)
